---
# 03_jira_efs.yml

- name: Create JIRA directory
  become: yes
  file:
    path: "{{ efs_jira_base_dir }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"

- name: Update JIRA Home directory permissions
  become: yes
  file:
    path: "{{ efs_jira_base_dir }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
#    recurse: yes

- name: Mount JIRA Home Dir on EFS Volume
  become: yes
  mount:
    path: "{{ efs_jira_base_dir }}"
    src: "{{ jira_data_volume_id }}"
    fstype: efs
    opts: tls
    state: mounted
  register: efs_mounted

- name: output debug
  debug: var=efs_mounted

- name: Create JIRA Shared Home directory
  block:
    - name: Create JIRA Shared Home directory
      become: yes
      file:
        path: "{{ efs_jira_base_dir }}/{{ src_shared_home}}"
        state: directory
        owner: "{{ jira_user }}"
        group: "{{ jira_group }}"

    - name: Update JIRA Shared Home directory permissions
      become: yes
      file:
        path: "{{ efs_jira_base_dir }}/{{ src_shared_home}}"
        owner: "{{ jira_user }}"
        group: "{{ jira_group }}"
        mode: 0755
  when: not efs_mounted.failed

# Check EFS for AWS Backup directory
# Moves files into place
# Remove AWS Backup directory
#- include: backup_placement.yml
#  when: restore_from_backup
