---
# 03_jira_efs.yml

- name: Create JIRA Home directory
  become: yes
  file:
    path: "{{ jira_home }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"

- name: Update JIRA Home directory permissions
  become: yes
  file:
    path: "{{ jira_home }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    recurse: yes

- name: Mount JIRA Home Dir on EFS Volume
  become: yes
  mount:
    path: "{{ jira_home }}"
    src: "{{ jira_data_volume_id }}"
    fstype: efs
    opts: tls
    state: mounted

# Check EFS for AWS Backup directory
# Moves files into place
# Remove AWS Backup directory
#- include: backup_placement.yml
#  when: restore_from_backup
