---
# 05_jira_container.yml
- name: ecs-stopped
  service:
    name: ecs
    state: stopped

## For quick testing and restarting
- name: Create Docker-compose file
  template:
    src: "docker-compose.yml.j2"
    dest: "/root/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: 0744

- name: Start Jira Service Management container
  docker_container:
    name: jira
    image: atlassian/jira-servicemanagement
    state: started
    restart: yes
    ports:
      - 8080:8080
    env:
      CLUSTERED: "true"
      ATL_JDBC_URL: "jdbc:postgresql://{{ jira_db_host }}:5432/jira?targetServerType=master"
      ATL_JDBC_USER: "jira"
      ATL_DB_DRIVER: "org.postgresql.Driver"
      ATL_DB_TYPE: "postgresaurora96"
      ATL_DB_SCHEMA_NAME: "public"
      ATL_JDBC_PASSWORD: "{{ jira_db_user_password }}"
      ATL_PROXY_NAME: "{{ alb_fqdn }}"
      ATL_PROXY_PORT: "443"
      ATL_TOMCAT_SCHEME: "https"
      ATL_TOMCAT_SECURE: "true"
      JVM_MINIMUM_MEMORY: "1536m"
      JVM_MAXIMUM_MEMORY: "3072m"
      JVM_RESERVED_CODE_CACHE_SIZE: "1024m"
      JIRA_HOME: "{{ container_jira_home }}"
      JIRA_SHARED_HOME: "{{ container_jira_shared_home }}"
      volumes:
        - "{{ src_jira_home }}:{{ container_jira_home }}"
        - "{{ src_shared_home }}:{{ container_jira_shared_home }}"
